# CMake generated Testfile for 
# Source directory: /Users/nicolasdubuisson/GitHub/lightup
# Build directory: /Users/nicolasdubuisson/GitHub/lightup/Text
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testv1_default "./game_test" "default")
set_tests_properties(testv1_default PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;45;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv1_default_solution "./game_test" "default_solution")
set_tests_properties(testv1_default_solution PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;46;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv1_print "./game_test" "print")
set_tests_properties(testv1_print PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;47;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv1_new "./game_test" "new")
set_tests_properties(testv1_new PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;50;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv1_new_empty "./game_test" "new_empty")
set_tests_properties(testv1_new_empty PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;51;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv1_copy "./game_test" "copy")
set_tests_properties(testv1_copy PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;52;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv1_equal "./game_test" "equal")
set_tests_properties(testv1_equal PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;53;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv1_delete "./game_test" "delete")
set_tests_properties(testv1_delete PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;54;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv1_get_square "./game_test" "get_square")
set_tests_properties(testv1_get_square PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;55;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv1_set_square "./game_test" "set_square")
set_tests_properties(testv1_set_square PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;56;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv1_get_state "./game_test" "get_state")
set_tests_properties(testv1_get_state PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;57;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv1_get_flags "./game_test" "get_flags")
set_tests_properties(testv1_get_flags PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;58;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv1_is_state "./game_test" "is_state")
set_tests_properties(testv1_is_state PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;59;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv1_has_flag "./game_test" "has_flag")
set_tests_properties(testv1_has_flag PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;60;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv1_play_move "./game_test" "play_move")
set_tests_properties(testv1_play_move PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;61;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv1_check_move "./game_test" "check_move")
set_tests_properties(testv1_check_move PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;62;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv1_restart "./game_test" "restart")
set_tests_properties(testv1_restart PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;63;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv1_update_flags "./game_test" "update_flags")
set_tests_properties(testv1_update_flags PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;64;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv1_is_over "./game_test" "is_over")
set_tests_properties(testv1_is_over PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;65;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv2_new_ext "./game_test" "new_ext")
set_tests_properties(testv2_new_ext PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;70;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv2_new_empty_ext "./game_test" "new_empty_ext")
set_tests_properties(testv2_new_empty_ext PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;71;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv2_game_1d "./game_test" "game_1d")
set_tests_properties(testv2_game_1d PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;72;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv2_equal_ext "./game_test" "equal_ext")
set_tests_properties(testv2_equal_ext PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;73;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv2_copy_ext "./game_test" "copy_ext")
set_tests_properties(testv2_copy_ext PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;74;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv2_game_wrapping_2x2 "./game_test" "game_wrapping_2x2")
set_tests_properties(testv2_game_wrapping_2x2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;75;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv2_game_wrapping_3x3 "./game_test" "game_wrapping_3x3")
set_tests_properties(testv2_game_wrapping_3x3 PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;76;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv2_game_wrapping_5x3 "./game_test" "game_wrapping_5x3")
set_tests_properties(testv2_game_wrapping_5x3 PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;77;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv2_game_wrapping_error "./game_test" "game_wrapping_error")
set_tests_properties(testv2_game_wrapping_error PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;78;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv2_undo_one "./game_test" "undo_one")
set_tests_properties(testv2_undo_one PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;79;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv2_undo_redo_some "./game_test" "undo_redo_some")
set_tests_properties(testv2_undo_redo_some PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;80;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv2_undo_redo_all "./game_test" "undo_redo_all")
set_tests_properties(testv2_undo_redo_all PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;81;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(testv2_restart_undo "./game_test" "restart_undo")
set_tests_properties(testv2_restart_undo PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;82;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(test_game_save "./game_test" "game_save")
set_tests_properties(test_game_save PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;85;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(test_game_load "./game_test" "game_load")
set_tests_properties(test_game_load PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;86;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(test_game_nb_solutions "./game_test" "game_nb_solutions")
set_tests_properties(test_game_nb_solutions PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;87;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
add_test(test_game_solve "./game_test" "game_solve")
set_tests_properties(test_game_solve PROPERTIES  _BACKTRACE_TRIPLES "/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;88;add_test;/Users/nicolasdubuisson/GitHub/lightup/CMakeLists.txt;0;")
